// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: Record_Play_Demo

#include "ui.h"

extern int play_flag;
extern int record_flag;

void record_func(lv_event_t * e)
{
	// Your code here
	record_flag = 1;
}

void play_func(lv_event_t * e)
{
	// Your code here
	play_flag = 1;
}
